version: '3.8'

services:
  django:
    build: ./
    command: gunicorn stocks_products.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/django/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env
  db:
      image: postgres:13.0-alpine
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      environment:
        - POSTGRES_USER=${DB_USER}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
        - POSTGRES_DB=${DB_DATABASE}
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/django/staticfiles
    ports:
      - 1337:80
    depends_on:
      - django

volumes:
  postgres_data:
  static_volume: